DROP TABLE APP_JADE_CP CASCADE CONSTRAINT PURGE;
CREATE TABLE APP_JADE_CP (
	AGENT_ID	VARCHAR2(20) PRIMARY KEY,
	CP_ID		VARCHAR2(20) NOT NULL,
	CP_NM		VARCHAR2(50),
	CP_CLS		VARCHAR2(1)	 NOT NULL,
	START_DT	VARCHAR2(8),
	END_DT		VARCHAR2(8),
	CONFIRM		VARCHAR2(1)	 NOT NULL,
	REG_DH		VARCHAR2(14),
	REG_ID		VARCHAR2(20),
	UPT_DH		VARCHAR2(14),
	UPT_ID		VARCHAR2(20),
	PG_ID		VARCHAR2(8),
	PG_NM		VARCHAR2(50),
	COM_CD		VARCHAR2(10),
	KSCC_TC_ID	VARCHAR2(9),
	SETTLE_YN	CHAR(1),
	SYNC_URL	VARCHAR2(100),
	CRYPTO_KEY	VARCHAR2(64)
);

CREATE INDEX IDX_JADE_CP_ID ON APP_JADE_CP('CP_ID');
CREATE INDEX IDX_JADE_CP_PG_ID ON APP_JADE_CP('PG_ID');
CREATE INDEX IDX_JADE_CP_COM_CD ON APP_JADE_CP('COM_CD');

COMMENT ON TABLE APP_JADE_CP IS 'JADE : 가맹점 정보';
COMMENT ON COLUMN APP_JADE_CP.AGENT_ID     IS '가맹점 관리번호';
COMMENT ON COLUMN APP_JADE_CP.CP_ID        IS '가맹점 ID';
COMMENT ON COLUMN APP_JADE_CP.CP_NM        IS '가맹점 명';
COMMENT ON COLUMN APP_JADE_CP.CP_CLS       IS 'CP종류 1:온라인 모바일직가맹, 2:온라인 모바일영업대행';
COMMENT ON COLUMN APP_JADE_CP.START_DT     IS '개통일자';
COMMENT ON COLUMN APP_JADE_CP.END_DT       IS '종료일자';
COMMENT ON COLUMN APP_JADE_CP.CONFIRM      IS '0:서비스중지, 1:CP요청상태, 2:사업부 승인 상태, 3:관리부서 최종 승인';
COMMENT ON COLUMN APP_JADE_CP.REG_DH       IS '등록일시';
COMMENT ON COLUMN APP_JADE_CP.REG_ID       IS '입력 ID';
COMMENT ON COLUMN APP_JADE_CP.UPT_DH       IS '수정일시';
COMMENT ON COLUMN APP_JADE_CP.UPT_ID       IS '업데이트 ID';
COMMENT ON COLUMN APP_JADE_CP.PG_ID        IS 'PG가맹점 ID';
COMMENT ON COLUMN APP_JADE_CP.PG_NM        IS 'PG가맹점 명';
COMMENT ON COLUMN APP_JADE_CP.COM_CD       IS '수수료 코드(TBYIM200.ENTPRI_CD종류)';
COMMENT ON COLUMN APP_JADE_CP.KSCC_TC_ID   IS 'KSCC 단말기 코드(TBCOM102.KSCC_TC_ID)';
COMMENT ON COLUMN APP_JADE_CP.SETTLE_YN    IS '정산대상 유무(Y/N)';
COMMENT ON COLUMN APP_JADE_CP.SYNC_URL     IS '결제요청 및 결제결과 회신URL';
COMMENT ON COLUMN APP_JADE_CP.CRYPTO_KEY   IS 'CP 암호화 키';
