DROP TABLE APP_JADE_PAY CASCADE CONSTRAINT PURGE;
CREATE TABLE APP_JADE_PAY (
	PAY_SER			CHAR(20)		NOT NULL PRIMARY KEY,
	GUBUN			CHAR(2)			NOT NULL,
	REQ_STAT		CHAR(1)			NOT NULL,
	CARD_TYPE		CHAR(1),
	CARD_ID			CHAR(16),
	CARD_SEQ		VARCHAR2(10),
	MOBILE_NO		VARCHAR2(11),
	PLATFORM		VARCHAR2(2),
	APP_VER			VARCHAR2(3),
	PHONE_MODEL		VARCHAR2(30),
	UUID			VARCHAR2(40),
	CP_CLS			VARCHAR2(2)		NOT NULL,
	CP_ID			VARCHAR2(8)		NOT NULL,
	CP_NM			VARCHAR2(50)	NOT NULL,
	USER_NO			VARCHAR2(20),
	USER_NM			VARCHAR2(50),
	PROD_CD			VARCHAR2(30),
	PROD_NM			VARCHAR2(100),
	ORDER_ID		VARCHAR2(50)	NOT NULL,
	CP_REQ_DH		CHAR(14),
	OTA_CLS			VARCHAR2(2),
	KEYSET_VER		VARCHAR2(2),
	KEY_VER			VARCHAR2(2),
	ALGORITHM_ID	VARCHAR2(2),
	BFR_AMT			NUMBER(10),
	REQ_AMT			NUMBER(10),
	AFT_AMT			NUMBER(10),
	SIGN1			VARCHAR2(8),
	SIGN2			VARCHAR2(8),
	SIGN3			VARCHAR2(8),
	SAM_ID			VARCHAR2(16),
	SAM_SEQ			VARCHAR2(10),
	CHIP_STAT_CODE	VARCHAR2(4),
	BFR_SAM_ID		VARCHAR2(16),
	BFR_CARD_SEQ	VARCHAR2(10),
	BFR_DEAL_AMT	NUMBER(10),
	STATUS			CHAR(2),
	REPL_CD			CHAR(2),
	MSG				VARCHAR2(100),
	TELE_DIV		VARCHAR2(10),
	REQ_DH			CHAR(14)		NOT NULL,
	UPDT_DH			CHAR(14),
	CHECK_FLAG		VARCHAR2(2),
	BARCODE			VARCHAR2(12),
	CP_REPL_CD		VARCHAR2(10),
	CP_MSG			VARCHAR2(100),
	PG_ID			VARCHAR2(30),
	PG_NM			VARCHAR2(50),
	REF_PAY_SER		CHAR(20),
	CARD_CMPL_CD	VARCHAR2(2),
	PAY_METHOD_VAL	VARCHAR2(30),
	PARAM1			VARCHAR2(50),
	PARAM2			VARCHAR2(50),
	PARAM3			VARCHAR2(50),
	PAY_CERT_CODE	VARCHAR2(10)
);

CREATE INDEX IDX_JADE_PAY_CARD_ID ON APP_JADE_PAY('CARD_ID');
CREATE INDEX IDX_JADE_PAY_MOBILE_NO ON APP_JADE_PAY('MOBILE_NO');
CREATE INDEX IDX_JADE_PAY_CP_ID ON APP_JADE_PAY('CP_ID');
CREATE INDEX IDX_JADE_PAY_ORDER_ID ON APP_JADE_PAY('ORDER_ID');
CREATE INDEX IDX_JADE_PAY_REQ_DH ON APP_JADE_PAY('REQ_DH');
CREATE INDEX IDX_JADE_PAY_BARCODE ON APP_JADE_PAY('BARCODE');
CREATE INDEX IDX_JADE_PAY_REF_PAY_SER ON APP_JADE_PAY('REF_PAY_SER');

COMMENT ON TABLE APP_JADE_PAY IS 'JADE : 지불정보';
COMMENT ON COLUMN APP_JADE_PAY.PAY_SER        IS '지불거래번호';
COMMENT ON COLUMN APP_JADE_PAY.GUBUN          IS '요청구분 01 : 결제요청, AC : 취소(선불), AB : 부분취소(선불), FC : 취소(후불), FB : 부분취소(후불), NC : 취소(교통카드), NB : 부분취소(교통카드)';
COMMENT ON COLUMN APP_JADE_PAY.REQ_STAT       IS '요청상태구분 1: 거래대기, 2: 진행중, 3: 거래완료, X: 거래중지';
COMMENT ON COLUMN APP_JADE_PAY.CARD_TYPE      IS '결제카드 종류 A : 유심카드, N : 교통카드';
COMMENT ON COLUMN APP_JADE_PAY.CARD_ID        IS '티머니카드번호';
COMMENT ON COLUMN APP_JADE_PAY.CARD_SEQ       IS '티머니카드거래일련번호';
COMMENT ON COLUMN APP_JADE_PAY.MOBILE_NO      IS '휴대폰번호';
COMMENT ON COLUMN APP_JADE_PAY.PLATFORM       IS '모바일플랫폼종류';
COMMENT ON COLUMN APP_JADE_PAY.APP_VER        IS '앱버전';
COMMENT ON COLUMN APP_JADE_PAY.PHONE_MODEL    IS '휴대폰모델';
COMMENT ON COLUMN APP_JADE_PAY.UUID           IS 'UICCID';
COMMENT ON COLUMN APP_JADE_PAY.CP_CLS         IS '"CP종류 1:직가맹점(CP), 2 : PG가맹점(PG)';
COMMENT ON COLUMN APP_JADE_PAY.CP_ID          IS 'CP_ID';
COMMENT ON COLUMN APP_JADE_PAY.CP_NM          IS 'CP명';
COMMENT ON COLUMN APP_JADE_PAY.USER_NO        IS '티모넷고객관리번호';
COMMENT ON COLUMN APP_JADE_PAY.USER_NM        IS '고객명';
COMMENT ON COLUMN APP_JADE_PAY.PROD_CD        IS '상품코드';
COMMENT ON COLUMN APP_JADE_PAY.PROD_NM        IS '상품명';
COMMENT ON COLUMN APP_JADE_PAY.ORDER_ID       IS 'CP주문번호';
COMMENT ON COLUMN APP_JADE_PAY.CP_REQ_DH      IS 'CP요청일시';
COMMENT ON COLUMN APP_JADE_PAY.OTA_CLS        IS '고객권종정보';
COMMENT ON COLUMN APP_JADE_PAY.KEYSET_VER     IS '키셋버전';
COMMENT ON COLUMN APP_JADE_PAY.KEY_VER        IS 'VK';
COMMENT ON COLUMN APP_JADE_PAY.ALGORITHM_ID   IS '알고리즘ID';
COMMENT ON COLUMN APP_JADE_PAY.BFR_AMT        IS '전잔액';
COMMENT ON COLUMN APP_JADE_PAY.REQ_AMT        IS '지불요청금액';
COMMENT ON COLUMN APP_JADE_PAY.AFT_AMT        IS '지불후잔액';
COMMENT ON COLUMN APP_JADE_PAY.SIGN1          IS 'SIGN1';
COMMENT ON COLUMN APP_JADE_PAY.SIGN2          IS 'SIGN2';
COMMENT ON COLUMN APP_JADE_PAY.SIGN3          IS 'SIGN3';
COMMENT ON COLUMN APP_JADE_PAY.SAM_ID         IS 'SAM_ID';
COMMENT ON COLUMN APP_JADE_PAY.SAM_SEQ        IS 'SAM_SEQ';
COMMENT ON COLUMN APP_JADE_PAY.CHIP_STAT_CODE IS '칩상태코드';
COMMENT ON COLUMN APP_JADE_PAY.BFR_SAM_ID     IS '이전SAM_ID';
COMMENT ON COLUMN APP_JADE_PAY.BFR_CARD_SEQ   IS '이전SAM일련번호';
COMMENT ON COLUMN APP_JADE_PAY.BFR_DEAL_AMT   IS '이전지불금액';
COMMENT ON COLUMN APP_JADE_PAY.STATUS         IS '상태코드 05 : 지불성공, A5 : 지불성공(Ack 성공), 01 : 지불실패, 02 : 지불후미확인, 03 : 지불후미확인, 04 : 지불후미확인, B0 : Sign3 결과가 공백(2020)';
COMMENT ON COLUMN APP_JADE_PAY.REPL_CD        IS '응답코드';
COMMENT ON COLUMN APP_JADE_PAY.MSG            IS '결과 메시지 ';
COMMENT ON COLUMN APP_JADE_PAY.TELE_DIV       IS '통신사구분 ';
COMMENT ON COLUMN APP_JADE_PAY.REQ_DH         IS '요청일시 ';
COMMENT ON COLUMN APP_JADE_PAY.UPDT_DH        IS '수정일시 ';
COMMENT ON COLUMN APP_JADE_PAY.CHECK_FLAG     IS '최종거래체크 유무 ';
COMMENT ON COLUMN APP_JADE_PAY.BARCODE        IS '환불티코인 바코드/환불번호';
COMMENT ON COLUMN APP_JADE_PAY.CP_REPL_CD     IS 'PG응답 ';
COMMENT ON COLUMN APP_JADE_PAY.CP_MSG         IS 'PG응답 메시지 ';
COMMENT ON COLUMN APP_JADE_PAY.PG_ID          IS 'PG ID ';
COMMENT ON COLUMN APP_JADE_PAY.PG_NM          IS 'PG 명 ';
COMMENT ON COLUMN APP_JADE_PAY.REF_PAY_SER    IS '취소 원거래번호';
COMMENT ON COLUMN APP_JADE_PAY.CARD_CMPL_CD   IS '카드사 구분코드';
COMMENT ON COLUMN APP_JADE_PAY.PAY_METHOD_VAL IS '가상카드번호';
COMMENT ON COLUMN APP_JADE_PAY.PARAM1         IS 'CP사용 파라미터1';
COMMENT ON COLUMN APP_JADE_PAY.PARAM2         IS 'CP사용 파라미터2';
COMMENT ON COLUMN APP_JADE_PAY.PARAM3         IS 'CP사용 파라미터3';
COMMENT ON COLUMN APP_JADE_PAY.PAY_CERT_CODE  IS '인증코드';
